steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/praxis-life-212209/go-xociety:v0.0.29', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/praxis-life-212209/go-xociety:v0.0.29']
  #- name: 'gcr.io/cloud-builders/kubectl'
  #args: ['set', 'image', 'deployment/go-xociety', 'go-xociety=gcr.io/praxis-life-212209/go-xociety:v0.0.17']
  #env:
  #- 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  #- 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
